### ISSUE TITLE
Sidekick dependencies compatible with sitecore installation?

### ISSUE THREAD

**Issue by PaulLoe** [JeffDarchuk/SitecoreSidekick#11]
If I install Sidekick with the nuget package, it comes with dependecies like "Microsoft.AspNet.Mvc", which is the System.Web.Mvc.dll. Is this System.Web.Mvc.dll compatible with the System.Web.Mvc.dll from the sitecore installation, because it will get overridden?

**Comment by JeffDarchuk** [comment]
Sitecore will function normally with asp 5.2.3, however prior to 8.1 Sitecore shipped with 5.1.2.  This is being addressed in sidekick version 1.3, so after 1.3 gets released it will not try to install the aspnet nuget package.  However, if you are unable to modify your asp version, or just don't want to, feel free to use 1.0.1 as this version didn't leverage MVC.
