### ISSUE TITLE
SCS CM enhancements

### ISSUE THREAD

**Issue by kamsar** [JeffDarchuk/SitecoreSidekick#12]
Based on IRL conversation just now:

- moving system fields diff option into diff panel (disable option if all diffs in system fields)
- diff supporting multiple versions in one language
- option to snipe single field value from equivalent remote version in diff view

- some sort of advanced checksum that enables diff icons to show (at least on a per item level) diffs without system fields applied

**Comment by kamsar** [comment]
* Checksumming needs to take lang + version into account
* Add a help note that you can ctrl-click to choose more than one root item (inside the tree pane)

**Comment by JeffDarchuk** [comment]
This is all fixed except for the ability to snipe an individual field value.  Still thinking about that one.
