### ISSUE TITLE
Content Migrator Error Handling

### ISSUE THREAD

**Issue by kamsar** [JeffDarchuk/SitecoreSidekick#13]
The `Rainbow.Storage.Sc.Deserialization.TemplateMissingFieldException` should be caught and handled as a warning, as opposed to an error as it is informational.

e.g.

![image](https://user-images.githubusercontent.com/103677/27094164-1121d96a-501e-11e7-8de7-38bfd755d355.png)

**Comment by JeffDarchuk** [comment]
this has been fixed in the latest version under a warning tab
