### ISSUE TITLE
False authenticationSecret mismatch

### ISSUE THREAD

**Issue by sonnendeck** [JeffDarchuk/SitecoreSidekick#19]
Hello,

we installed _Sitecore Sidekick Foundation_ and the _Content Migrator_ via Nuget Package and did setup the configurations as indicated in the examples. Each client can select the other client in the drop down menu an error is shown indicating that the secret is different. The authenticationSecret is the same on both clients, because we use the same file. Also the secret does contain only numbers and characters. 

Any idea what could be the reason or where we should investigate further?

Best regards
Martin

We are using:

SitecoreSidekickFoundation 1.3.2
SitecoreSidekickContentMigrator 1.3.2
Sitecore 8.2

**Comment by JeffDarchuk** [comment]
Hello Martin,

  The system interprets any forbidden status code as a possible security key mismatch, check to make sure you don't have a firewall or some other network blocking tool that could be bouncing it back with a 403 status code.

  Also the security protocols require that the URL sent to the server be the same url that is received.  If you have some network tooling that adds query string parameters, for example, it will fail validation as this would be seen as a possible attack vector.  Similarly, if additional parameters are added to a post request, the system will reject it.  Finally if any parameters are modified in transit the system will also reject it.  In short, the request payload leaving the source server must match the request payload entering the target server without modification or else it will be seen as an attack.

Content migrator is using a slighly modified version of [microchap](https://github.com/kamsar/MicroCHAP) if you would like to read up on it further.

**Comment by JeffDarchuk** [comment]
closing this issue, as haven't heard any updates.
