### ISSUE TITLE
Support lightweight deployment without the need to install items

### ISSUE THREAD

**Issue by michaellwest** [JeffDarchuk/SitecoreSidekick#24]
Working on content migration and have received a request to not install items in the CE. The desired outcome is for only code and config deployed, then migration takes place through the PowerShell module provided.

**Comment by JeffDarchuk** [comment]
1.4.3 supports this now.  in the zSCS.config there is a new property in the initialize processor of 
<DisableItemGeneration>false</DisableItemGeneration>

change that to true to disable the items from being generated.  Additionally if you want to disable the UI entirely on that server, delete out the <clientscripts> and <commands> nodes in that same config file and SCS won't be invokeable from the interface anymore (but the services will still work)

**Comment by michaellwest** [comment]
That's great news! Thank you.
