### ISSUE TITLE
Unable to enable Sidekick for appropriate role.

### ISSUE THREAD

**Issue by AlexeyLyndin** [JeffDarchuk/SitecoreSidekick#28]
How should modify  zSCSAuditLog/zSCSContentMigrator/zSCSEditingContext config files to enable Sidekick only for "sitecore\Developer" role?

Variants like "sitecore\Developer", "sitecore\developer", "Developer", "developer" do not work!

**Comment by JeffDarchuk** [comment]
Hmm, that may be a bug, i'll investigate.

**Comment by AlexeyLyndin** [comment]
@JeffDarchuk hmmm, looks stragne. I've created user with developers role and then changed all 3 config files. However after login as a developer I could not find Sidekick.

**Comment by JeffDarchuk** [comment]
did you try the key command shift+alt+s?  I think by default the start menu button doesn't show to non-admins.

**Comment by AlexeyLyndin** [comment]
Yes, shift+alt+s shows me popup. But.... I don't think this is cool to have such behavior IMHO. As admin you could navigate to Sidekick via button like  Windows start button. But when you are not admin you should remember about this button combination.

**Comment by JeffDarchuk** [comment]
that's fair, it's definitely a bug and i'll get it fixed up for the next release.  In the mean time feel free to manually make the security changes needed to make it appear.  Thanks for the bug report.

**Comment by JeffDarchuk** [comment]
Default security on the item has been fixed so it should show up for authors in 1.5-rc2.
