### ISSUE TITLE
Sidekick is not showing the right differences from remote and local system

### ISSUE THREAD

**Issue by squadwuschel** [JeffDarchuk/SitecoreSidekick#30]
hi, I got some problems that sidekick is not showing if the item is the same locally and remote.

I am using Sitecore 9.0.2 with SXA and for item sync I am using unicorn and for content sync I would use sidekick. The SXA nodes on my remote systems where created with unicorn.

In the below example the complete Data List inclusive Subitems is under Unicorn control, but the items below each Data Item are not under unicorn control. I've just synced the hole data Tree with sidekick don't know if this was right, but after that it shows me that nearly all items are different

![grafik](https://user-images.githubusercontent.com/1572878/44894636-0f625b00-acf1-11e8-92d4-6e622c34ef81.png)

and here the home Folder is under unicorn control but not the subitems. I've pulled the subitems from my remote system and after that they are not shown as equally "green"

![grafik](https://user-images.githubusercontent.com/1572878/44894739-9dd6dc80-acf1-11e8-9632-cbee1d024ce8.png)

let me know when you need more Informations. I've used the latest stable nuget package from sitekick.

**Comment by JeffDarchuk** [comment]
if you click the red box, it will show you a diff of what is wrong.  Which fields is it reporting is updated?  Under the hood it uses the system revision field to calculate equality.  Basically whenever a save is made a new guid is generated for the item, therefore if the guid is the same locally and remotely then the item is reported unchanged.

**Comment by squadwuschel** [comment]
k thx, strange I've tested it today again and now it seems to work right. the synced fields are shown in Green.
