### ISSUE TITLE
Error 400 - Bad Request when signed in with different users

### ISSUE THREAD

**Issue by sebastianlay** [JeffDarchuk/SitecoreSidekick#31]
After using Sitecore with three or four different users (each editing a number of items) the Content Editor throws an "Error 400 - Bad Request" which makes the whole Sitecore backend unusable.

As far as I can see this is caused by the Editor Context module, which saves a base64-encoded list of last viewed items which get saved into the "scseditorcontext[username]" cookie. This cookie can reach a size of over 2500 bytes. Having a few of those cookies you can reach the limit for the HTTP request headers which is typically 8K.

**Comment by JeffDarchuk** [comment]
Ah yes, that is an accurate depiction of what's happening.  Fascinating that it can get so large,  I'll make sure to remedy that in the next minor release that's happening soon.  For now feel free to remove the editing context registration configuration to disable that sidekick app if it's impacting your work.

**Comment by sebastianlay** [comment]
Thanks for the quick reply!

For anyone else having this problem: I had to disable both the _zSCSEditingContext.config_ and _zSCSAuditLog.config_ in order for the cookies to disappear.
Probably because of this line:
`<processor type="ScsEditingContext.Pipelines.HttpRequestBegin.RegisterEvent, ScsEditingContext" />`

Additionally I noticed an inconsistent behaviour regarding the expiration of these cookies. Initially they are set for one day. Later (after editing a second item?) this expiration date is changed to "end of session". I don't know whether this is the desired behaviour or not.

**Comment by JeffDarchuk** [comment]
Ah, yes, embarrassing that the processor is defined in the audit log config.  That can safely be removed.  I have verified the cookie expiration anomaly as well, i suspect it's got something to do with how the angularjs module i'm using handles cookies.  Likely as part of fixing the cookie size issue i'll be removing the cookie entirely so it likely won't be an issue moving forward.
