### ISSUE TITLE
Sitecore 9.1 release causes conflict in Rainbow dll versions

### ISSUE THREAD

**Issue by GenZodd** [JeffDarchuk/SitecoreSidekick#33]
With the release of Sitecore 9.1 I can't have unicorn and Sidekick installed anymore as Unicorn for 9.1 uses Rainbow version 2.0.4 but Sidekick wants version 2.0.0 so they fight each other to get the assembly they want deployed.

**Comment by GenZodd** [comment]
Here is some more info on this. I was able to get Sidekick to play nice with the newer dll be adding Sidekick to the same project where unicorn was added. By doing this it accepts the Rainbow assembly that is pulled in instead of pulling in its minimum version of 2.0.0. 

However, when I try and sync from dev to my local I get the following exception. So looks like it does not play nice with the new interface updates in 2.0.4.

     [MissingMethodException: Method not found: &#39;Void Rainbow.Storage.Sc.Deserialization.DefaultDeserializer..ctor(Rainbow.Storage.Sc.Deserialization.IDefaultDeserializerLogger, Rainbow.Filtering.IFieldFilter)&#39;.]
     ScsContentMigrator.&lt;&gt;c.&lt;InitializeContainer&gt;b__5_1(Object[] args) +0
     SitecoreSidekick.Shared.IoC.Container.Resolve(Object[] args) +117

    [Exception: The registered object for Rainbow.Storage.IDataStore could not be initialized. An unhandled exception occurred during object resolution. Check the inner exception for more information]
     SitecoreSidekick.Shared.IoC.Container.Resolve(Object[] args) +776
     ScsContentMigrator.Core.ContentItemInstaller..ctor() +313
     ScsContentMigrator.&lt;&gt;c.&lt;InitializeContainer&gt;b__5_4(Object[] args) +31
     SitecoreSidekick.Shared.IoC.Container.Resolve(Object[] args) +117

    [Exception: The registered object for ScsContentMigrator.Core.Interface.IContentItemInstaller could not be initialized. An unhandled exception occurred during object resolution. Check the inner exception for more information]
     SitecoreSidekick.Shared.IoC.Container.Resolve(Object[] args) +776
     ScsContentMigrator.Core.ContentMigration..ctor() +338
     ScsContentMigrator.Services.ContentMigrationManagerService.StartContentMigration(PullItemModel model) +217
     ScsContentMigrator.ContentMigrationController.StartOperation(PullItemModel data) +463
     lambda_method(Closure , ControllerBase , Object[] ) +139

**Comment by JeffDarchuk** [comment]
Aww man.  Thanks for bringing this to my attention, luckily i'm about to release a release candidate for Sidekick 1.5 and i'll make sure these things get addressed.  I expect to have it resolved in the RC within the week and i'll keep you informed.

**Comment by GenZodd** [comment]
Great to hear! Love the tool BTW.

**Comment by JeffDarchuk** [comment]
This issue is now fixed in the 1.5.0-rc1.  This does however include some breaking changes that means you'll need to deploy it out to your source server as well as your target server since i changed the contract between them to be more efficient as another improvement in 1.5.
