### ISSUE TITLE
Sourcecode for Sitecore 7.2 version of Sidekick

### ISSUE THREAD

**Issue by ravikumarmvs** [JeffDarchuk/SitecoreSidekick#35]
Hi,
Is there any way you could point me to the Sourcecode (Revision number) for Sitecore 7.2 version of Sidekick? Because current version seems to be supporting 8.2+ version with dependency injection and a lot of other enhanced SDKs of Sitecore 8.2+.

**Comment by JeffDarchuk** [comment]
The source code is the same for all supported versions.  Are you having a particular problem?  I made sure to omit things like MS DI and item API changes, keeping with the bare bones functionality of each.  Let me know if there's a problem i can help with.

**Comment by ravikumarmvs** [comment]
Yes Jeff. Even build fails if I use 7.2 version of Sitecore kernal dll. Dependency injection and Some of the search sdks are not supported I guess.

**Comment by ravikumarmvs** [comment]
Actually I want to introduce Language name on Audit log screen. Since we work on Sitecore 7.2, I would like to edit that specific revision of code.

**Comment by JeffDarchuk** [comment]
You might need to add in development dependencies for higher versions of the sitecore binaries in order to get it to compile, it should work at runtime with the 7.2 binaries.

**Comment by ravikumarmvs** [comment]
I'll give it a try. But I think it may throw a run time exception.
