### ISSUE TITLE
"Not logged in." message after install

### ISSUE THREAD

**Issue by frasermcarthur** [JeffDarchuk/SitecoreSidekick#37]
Hi,

We've just installed the Content Migrator using the Nuget package, however when I try to open it within Sitecore I am seeing the following message: "Not logged in.
Log into Sitecore to use Sidekick."

I have logged in however the message persists. Any idea what could be causing this?

Thanks

**Comment by frasermcarthur** [comment]
Managed to resolve this. We have a CSP in place which was stopping the required js and css files from loading. Once I whitelisted the sources it worked as intended.

**Comment by GenZodd** [comment]
Where did you change the CSP? I am getting the same error. We have had Sidekick working for months and all of a sudden we are now getting this. I don't see anything being blocked though.

**Comment by JeffDarchuk** [comment]
CSPs are something that's custom controlled.  Generally you can apply them to your web.config or a more robust and SC friendly way is to apply them via a pipeline processor, i'd start looking there.

More generally you can receive this error whenever your session cookies aren't identified as logged in within Sitecore.  This is to prevent people with expired sessions from operating Sidekick.

Additionally it's possible that a catastrophic JS error could potentially cause this message to appear.  Any JS errors on the console?

**Comment by GenZodd** [comment]
No JS errors or any for that matter in the console. It seems to have broken in only an active development branch but there seems to be no config patches that would have impacted this (Added a new field type, updated unicorn sync config, deleted a patch config).

**Comment by GenZodd** [comment]
Tracked it down. We are adding a response filter that is steppign on a resposne filter Sidekick has in place.

**Comment by JeffDarchuk** [comment]
ah yes, that would certainly do it.  Glad you found it!
