### ISSUE TITLE
Sitecore Dropdowns are getting cropped

### ISSUE THREAD

**Issue by PaulLoe** [JeffDarchuk/SitecoreSidekick#39]
The Dropdowns in the sitecore backend are getting cropped because Sidekick renders a additional div on that request that is not needed. 

![image](https://user-images.githubusercontent.com/26430873/56670604-71723500-66b3-11e9-8104-370b2e456d40.png)

In the scscommand.js file are allready checks for that situation but they need to be reviewed. The Dropdowns are rendering a Iframe with a url like 
`http://sitename/sitecore/shell/default.aspx?xmlcontrol=Gallery.Archives&id=...&la=en&vs=1&db=master&sc_content=master&ShowEditor=1&Ribbon.RenderTabs=true`

**Comment by AlexKasaku** [comment]
We're encountering this same issue on Sitecore 9.1

**Comment by paulmains** [comment]
The response I got from sitecore when they were debugging the issue (I wasn't aware that it was sidekick at the time) was the following.

> Hello Paul,
> 
> I have investigated your fiddler session and found out that the issue is in your custom java-script /SCS/platform/resources/scscommand.js file.
> 
> The scscommand.js file uses document.write() function which is considered a bad practice and can lead to bugs. 
> 
> I was able reproduced your issue on my local machine and fixed it by using document.innerHtml property instead of document.write() function.
> 
> Please perform following steps to fix the issue:
> 
> Step 1: Replace the following line in /SCS/platform/resources/scscommand.js file.
> 
>     document.write("<div id='scs' style='display:none;height:100%;width:100%;position:absolute;z-index:9999;left:0;top:0;'></div>");
>     
> with the below line:
> 
>     document.innerHTML += "<div id='scs' style='display:none;height:100%;width:100%;position:absolute;z-index:9999;left:0;top:0;'></div>";
> 
> Step 2: Clear your browser cache and refresh your client. 
>     
> Please let me know if you have any questions or require any further assistance. 
> 
> Best regards,
> Amit

**Comment by JeffDarchuk** [comment]
To avoid this problem, feel free to comment out the <clientscripts> node in the zSCS.config file.  This powers the keyboard shortcuts so Sitecore Sidekick will function normally otherwise without it.

**Comment by JeffDarchuk** [comment]
Otherwise, i just pushed an update 1.5.1 that fixes this issue.  If you don't want to upgrade, feel free to remove the `clientScripts` node
