### ISSUE TITLE
TreelistEx migration issue?

### ISSUE THREAD

**Issue by Infarinato** [JeffDarchuk/SitecoreSidekick#40]
Hi, we have v1.5.2 of the Sitecore Sidekick NuGet package installed in all our environments, and have recently come across an issue with a TreelistEx field. (Please bear in mind that, although in our organization we’ve worked with Sitecore for a few years now, we don’t have a great knowledge of the inner workings of Sitecore and have no experience whatsoever with Unicorn, so this might well be an issue with Unicorn rather than Sidekick… or no issue at all. 😊)

Basically, we have an item with a TreelistEx field, which references _five_ items in our PROD environment. Now, when we try to pull that item into any of our non-PROD environments, that field clearly gets updated in the target environment, but only the _first one_ of those five referenced items ends up in the target environment —and, yes, all the referenced items do exist in all the environments.

If you then try to pull that item again, the Content Migrator seems to think the item in the target environment is the same as the one in PROD and nothing happens (we’ve tried this with several different combinations of the Content migration options and the Sitecore advanced options).

Is this a known issue, or is there something in our set-up that might cause this behaviour?

Many thanks.

**Comment by JeffDarchuk** [comment]
Did you check the raw values of the field?  It should be a pipe delimited list of guid strings.  If that's the same on the source and destination then your issue is likely elsewhere.

**Comment by Infarinato** [comment]
Thank you for getting back to me, Jeff. I did. The raw values just say `[Blob Value]` (in all environments). 😕

**Comment by JeffDarchuk** [comment]
Hmm, that is very puzzling, TreelistEx should have output like this:

> {E70AB833-C7A1-480B-867B-F839C5FAD411}|{AED99651-72A3-452A-B067-5EB1F3003EB5}

**Comment by Infarinato** [comment]
Right… It looks like we had the Blob checkbox ticked for that TreelistEx template field. After unticking it, raw values looked normal again, Sidekick started picking up the differences between environments and migrating items accordingly.  :blush: —I was surprised that you could actually tick that checkbox for that field type, and the reason why we had it that way still escapes me. :confused:

I think you can close this “issue” (sorry about the noise): the only thing I would say is that _in that very peculiar situation_ Sidekick (Unicorn?) doesn’t seem to pick up differences / migrate items correctly (whereas Sitecore built-in [un]packaging has no problems)…

**Comment by JeffDarchuk** [comment]
That is peculiar.  Honestly didn't know you could do that to a field.   It would definitely be an issue with the unicorn libraries as you suggested as Unicorn's `Rainbow` library is what controls the serialization and deserialization.  At any rate, glad you have it working again.
