### ISSUE TITLE
Checksum generation failed

### ISSUE THREAD

**Issue by monkey-ldb** [JeffDarchuk/SitecoreSidekick#41]
Hi,

our log got spammed by the following error 

`
32004 15:43:02 WARN  Checksum generation failed.
Exception: System.Data.SqlClient.SqlException
Message: Conversion failed when converting from a character string to uniqueidentifier.
Source: .Net SqlClient Data Provider
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at System.Data.SqlClient.SqlDataReader.Read()
   at ScsContentMigrator.Data.ChecksumGenerator.Generate(List`1 ids, String database)`

How to fix this?

**Comment by JeffDarchuk** [comment]
You may see this error if your database has items in it without IDs.  Generally this would not happen in normal Sitecore operation, but it can happen and usually indicates some kind of data corruption.  Try Identifying and removing entries that have a null or malformed guid for their ID out of the `Items` table.  You won't see any adverse effect on Sitecore by removing these entries as Sitecore can't utilize Items without a proper ID.

**Comment by monkey-ldb** [comment]
Could you explain, which column may be the reason?
Because the sql type is already uniqueidentifier,
which should normally keep away such malformed entries.
I can't find any broken entry, but the log is spammed with this log all the time.

Thanks in advance.

**Comment by JeffDarchuk** [comment]
that's exactly true, it should be protected.  Out of the box nothing within Sitecore iterates over the item table so under normal operation you may not notice this kind of problem.

Reviewing the query more closely there's a few other places that could result in this error message, please check for null, empty or malformed in the `Item` table's ParentID field as well as the `VersionedFields` ItemId field.  I would expect to see this error if any entry in either of those was malformed.

**Comment by monkey-ldb** [comment]
I extended the logging message and got this:

`WARN  Checksum generation failed. Executed sql: 
				WITH Roots AS (
					SELECT Id
					FROM Items
					where Id IN ('')
				), tree AS (
					SELECT x.ID, x.ParentID
					FROM Items x
					INNER JOIN Roots ON x.ID = Roots.ID
					UNION ALL
					SELECT y.ID, y.ParentID
					FROM Items y
					INNER JOIN tree t ON y.ParentID = t.ID
				)
				SELECT t.ID, t.ParentID, v.Value
				FROM tree t
				inner join VersionedFields v on v.ItemId = t.ID
				WHERE v.FieldId = '8cdc337e-a112-42fb-bbb4-4143751e123f'

, IDS: 
Exception: System.Data.SqlClient.SqlException
Message: Conversion failed when converting from a character string to uniqueidentifier.
Source: .Net SqlClient Data Provider
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at System.Data.SqlClient.SqlDataReader.Read()
   at ScsContentMigrator.Data.ChecksumGenerator.Generate(List`1 ids, String database) in `

It seems that the Ids list is empty, but I am not that familiar with the code to identity the reason.
Maybe because I dont use the ui to sync, maybe its called in the background somehow with empty parameter? The agent is not active (completely commented out).

**Comment by JeffDarchuk** [comment]
Ah, in that case i suspect you're missing roots definitions in your configuration file.  It currently requires at least one root to be defined.  These root definitions define what to use to generate the checksum as well as what content items to make available in the UI.  I suspect it will fix your issue to put in a path to any old item in Sitecore, if you're not using the UI a leaf node in the item tree will make the most sense.  I see your use case is a valid one however, so i'll make sure to get this fixed in the next version, thanks for bringing it to my attention.
`<?xml version="1.0"?>
<configuration xmlns:patch="http://www.sitecore.net/xmlconfig/">
	<sitecore>
		<pipelines>
			<scsRegister>
				<processor type="ScsContentMigrator.ContentMigrationRegistration, ScsContentMigrator">
					
					<AuthenticationSecret>too short sample</AuthenticationSecret>

					
					<roots hint="raw:BuildRoot">
						<root>/sitecore/content</root>
						<root>/sitecore/media library</root>
						<root>/sitecore/system/Marketing Control Panel</root>
					</roots>
					
					
					<servers hint="raw:BuildServerList">
						<server>[enter server 1 url here i.e. https://sitecore-qa-cm]</server>
						<server desc="optional label">[enter server 2 url here i.e. https://sitecore-prod-cm]</server>
					</servers>
				</processor>
			</scsRegister>
		</pipelines>
	</sitecore>
</configuration>`

**Comment by balaji-kandasamy** [comment]
I am seeing a similar issue while Sitecore TDS package install happens. 

> ManagedPoolThread #1 14:53:08 INFO  Job ended: Hhogdev.SitecorePackageDeployer.Tasks.InstallPackage (units processed: )
> 11172 14:53:10 WARN  Checksum generation failed.
> Exception: System.Data.SqlClient.SqlException
> Message: Transaction (Process ID 97) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
> Source: .Net SqlClient Data Provider
>    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
>    at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
>    at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
>    at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
>    at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
>    at System.Data.SqlClient.SqlDataReader.Read()
>    at ScsContentMigrator.Data.ChecksumGenerator.Generate(List`1 ids, String database)

My Root definition looks like this

`` <roots hint="raw:BuildRoot">
						<root>/sitecore</root>
						
					</roots>``

**Comment by yousleepy** [comment]
Does this particular issue cause the TDS package install to fail?  I'm unfamiliar with the details of how TDS goes it's work but as far as Sidekick is concerned an error like this is inconsequential as it will regenerate the checksum again after 2 minutes or a change is detected.
