### ISSUE TITLE
Sitecore 9.1.1 - SXA 1.8.1 - Uncaught TypeError: Cannot read property 'innerHTML' of null when opening the Sitecore backend pages

### ISSUE THREAD

**Issue by islamkhattab** [JeffDarchuk/SitecoreSidekick#43]
![image](https://user-images.githubusercontent.com/3328233/67978775-38ca8f80-fbf1-11e9-9d9b-edebcda86319.png)

JS Error: Uncaught TypeError: Cannot read property 'innerHTML' of null when opening the backend pages like Role Manager or Security Editor ... etc

/SCS/platform/resources/scscommand.js

![image](https://user-images.githubusercontent.com/3328233/67978997-c908d480-fbf1-11e9-8d37-d8dca7a7afe8.png)

**Comment by JeffDarchuk** [comment]
Hmm, is this causing any issues?  Or is it more just an annoying  console error?

This drives the keyboard shortcut for sidekick (ctr+shift+s).  It can be disabled via configs by removing this XML node: https://github.com/JeffDarchuk/SitecoreSidekick/blob/master/Source/SitecoreSidekick/zSCS.config#L25

Sidekick itself will still be accessible from the Sitecore start menu button, even when the shortcut is disabled.

This functionality has caused trouble in the past, due to it being added to all Sitecore pages,  In some cases, as you have found here, it doesn't quite work to wire it up.

At any rate i'll work to getting this fixed in the next release.

**Comment by tomunderhill** [comment]
I am seeing the same issue, and it is causing Sitecore errors (Sc 9.2), specifically a CSRF exception when creating new item versions. I've removed it as you suggested (thanks!).

Previously I'd got it working better by amending it to:

`window.onload = function () {

    var elemDiv = document.createElement('div');
    elemDiv.style.cssText = 'display:none;height:100%;width:100%;position:absolute;z-index:9999;left:0;top:0;';
    elemDiv.setAttribute("id", "scs");
    document.body.appendChild(elemDiv);

    //document.body.innerHTML += "<div id='scs' style='display:none;height:100%;width:100%;position:absolute;z-index:9999;left:0;top:0;'></div>";

    document.onkeydown = function (event) {
        var keyCode;

        if (window.event) // IE/Safari/Chrome/Firefox(?)
        {
            keyCode = event.keyCode;
        } else if (event.which) // Netscape/Firefox/Opera
        {
            keyCode = event.which;
        }

        var keyChar = String.fromCharCode(keyCode).toLowerCase();

        if (keyChar === "s" && event.shiftKey && event.altKey) {
            var scs = window.top.document.getElementById("scs");

            if (typeof (scForm) !== "undefined" && typeof (scForm.postEvent) !== "undefined")
                return scForm.postEvent(this, event, 'scs:open');

            if (scs.style.display === "block") {
                scs.style.display = "none";
                window.top.document.body.style.height = "";
            } else {
                if (!scs.innerHtml)
                    scs.innerHTML = "<iframe id='scs-iframe' frameBorder='0' style='width:100%;height:100%;background-color: transparent;' src='/scs/platform/scs.scs' />";
                scs.style.display = "block";
                scs.style.position = "absolute";
                window.top.scrollTo(0, 0);
                window.top.document.body.style.overflow = "hidden";
            }
            return false; // To prevent normal minimizing command
        } else if (keyCode === 27) {
            if (scs.style.display === "block") {
                scs.style.display = "none";
                window.top.document.body.style.overflow = "";
            }
        }
    };
};
`

**Comment by JeffDarchuk** [comment]
Tom, thanks for this, I've validated that your JS works far better than mine and I've cut a release for 1.5.3 that includes this code.  Thanks for the help!
