### ISSUE TITLE
Sidekick iframe on desktop not loading correct URL

### ISSUE THREAD

**Issue by ConorHowe** [JeffDarchuk/SitecoreSidekick#45]
Our current development sever has a url with a port different to the normal 80 or 443. The iframe url added when opening the Sidekick button on the Sitecore Desktop doesn't append the port number and therefore can't open the content migrator

**Comment by JeffDarchuk** [comment]
Thanks for bringing this to my attention, i'll work on getting this fixed for the next update.  In the meantime you can go directly to [host with port]/scs/platform/scs.scs to access the functionality

**Comment by ConorHowe** [comment]
Thank you, Jeff
