### ISSUE TITLE
Not logged in

### ISSUE THREAD

**Issue by jesslich423** [JeffDarchuk/SitecoreSidekick#47]
Hello there. Just installed Content Migrator on my local instance and another environment. When I try to use it, all I see is "Not logged in" even though I am definitely logged in. Am I missing something? Thank you!

Jessica

![sidekickIssue](https://user-images.githubusercontent.com/61322532/75045614-97ae6000-5491-11ea-99b7-99488c28158e.PNG)

**Comment by JeffDarchuk** [comment]
I would expect to see this kind of issue if there was a javascript error.  does your dev tools console have errors?  Additionally i would check your Sitecore logs for exceptions related to Sidekick.

**Comment by jesslich423** [comment]
I actually noticed shortly after I posted this that I was getting CSP errors in the console when I would open up Sidekick.

**Comment by jesslich423** [comment]
I am still getting this error on /scs/platform/resources/main.js: `TypeError: vm.sidekick is undefined`. not sure if I'm still missing something or if this is actually a bug.

**Comment by JeffDarchuk** [comment]
any more console errors?  I would expect to see that if some javascript 404'd

**Comment by jesslich423** [comment]
the only other error i see is `Error: a.replace is not a function` which i don't understand because it's just coming from jquery..

**Comment by JeffDarchuk** [comment]
if you go to 
[your domain]/scs/platform/scs.scs?desktop=true
does the application function properly?

**Comment by jesslich423** [comment]
it does seem to be functioning, but i do still see the errors in the console.

![sidekickError](https://user-images.githubusercontent.com/61322532/75167505-751b8180-56f3-11ea-8f75-ead62185d70f.PNG)

**Comment by JeffDarchuk** [comment]
It looks like some assets aren't loading properly.  Do you have some CSPs in effect here?  Sidekick does use some public JS source repositories for jquery and fancybox.  Do you see any errors that your CSP is rejecting an outgoing request for assets?

**Comment by jesslich423** [comment]
yes, we do have CSPs in effect and i was able to find what I was missing. I now have no issues. Thank you for your help!

**Comment by JeffDarchuk** [comment]
Ah, super, glad you got it figured out!
