### ISSUE TITLE
[Feature Request] Presets for content migrator

### ISSUE THREAD

**Issue by michaellwest** [JeffDarchuk/SitecoreSidekick#48]
Would be nice if there is a way to save the selected items in the "content item to pull" area for reuse. It's not uncommon to want to pull on-demand the same parts of the tree. In the case of SXA, this gets really tedious.

![image](https://user-images.githubusercontent.com/933163/82903767-0e427a00-9f27-11ea-88b9-cc6fee339acd.png)

I could imagine a presets section where in just one click you rerun the preset steps. All the options that were checked are reused. 

Perhaps look something like this:

![image](https://user-images.githubusercontent.com/933163/82904124-a50f3680-9f27-11ea-99ed-3dac1799d3f0.png)

**Comment by JeffDarchuk** [comment]
A great idea, thanks for the inspiration.  Included in 1.5.6
