### ISSUE TITLE
[Feature Request] Don't override Desktop Button if it exists already

### ISSUE THREAD

**Issue by sebastianlay** [JeffDarchuk/SitecoreSidekick#49]
Hi,

thank you for the module and for continuing to update it!

During the initialization the `EnsureDesktopButton` method overrides some fields on the desktop button item and makes sure that the security field is set to `ar|sitecore\\Sitecore Client Authoring|pd|+item:read|pe|+item:read|`.
It would be nice if these rights could be customized (and not reset with every start) so the button is not shown to every editor. Or is there another reason the item has to have exactly these rights that I am not aware of?

I could also change the code myself and create a pull request if you'd prefer that.

Thanks!

**Comment by JeffDarchuk** [comment]
Security for Sidekick as a whole has read rights for everyone because the the individual apps are what control who can use what.  For example, say you don't want authors to have access to content migrator, you can define a particular role, user, or set it up as admin only.

**Comment by sebastianlay** [comment]
I see. In our particular case we are not using that many apps and we have some users that don't have access to any app and thus only see a blank grey window when opening the Sidekick window. It's really just a minor issue but it would be small improvement anyway.

**Comment by JeffDarchuk** [comment]
yeah, it would probably be relatively easy to only apply it if it's newly created or missing security.

**Comment by JeffDarchuk** [comment]
this will be included in the next minor release
