### ISSUE TITLE
Uncaught TypeError: Cannot read property 'innerHTML' of null

### ISSUE THREAD

**Issue by Jen-Pearson** [JeffDarchuk/SitecoreSidekick#52]
Recently having issues with my Sitecore 9.1.1 instance. Content editor is throwing a whole bunch of Uncaught TypeError: Cannot read property 'innerHTML' of null. Relating to scscommand.js:44 and jsnlog.min.js:1.

I recently had some dll issues (unrelated) but have checked I have the expected files:
![image](https://user-images.githubusercontent.com/8033039/87387721-a800dc00-c5e6-11ea-8758-1d94b46fbdc5.png)

and configs:
![image](https://user-images.githubusercontent.com/8033039/87387772-c070f680-c5e6-11ea-9904-087877962fc8.png)

The error:
![image](https://user-images.githubusercontent.com/8033039/87387856-e8605a00-c5e6-11ea-8ceb-a9972611325e.png)

This is on my local single instance environment.  I also recently installed a google invisible recaptcha package for sitecore which I have since removed as I thought it was responsible for these script errors until I realised it was sidekick related so I'm not sure if it's coincidence this happened at the same time or has somehow affected the sidekick files.

I don't use Unicorn at all.

**Comment by JeffDarchuk** [comment]
What version are you using?  This was reported and fixed a few months back, I suspect that upgrading to the latest will fix your issues.

**Comment by Jen-Pearson** [comment]
Using v1.5.2.  Where do I see what is current version? Thanks!

**Comment by Jen-Pearson** [comment]
OK - updating seems to have done the trick. Was surprising to find it just stop working but maybe I did update something accidentally.

**Comment by JeffDarchuk** [comment]
great, glad that worked.  Happy migrating!
