### ISSUE TITLE
AccessDeniedException when RemoveLocalNotInRemote is enabled

### ISSUE THREAD

**Issue by vitaliitylyk** [JeffDarchuk/SitecoreSidekick#54]
I am getting the following error during content migration, when `RemoveLocalNotInRemote` is enabled:

```
Sitecore.Exceptions.AccessDeniedException: User does not have the necessary rights to recycle the item (<ItemId>)
   at Sitecore.Diagnostics.Assert.HasAccess(Boolean accessAllowed, String message)
   at Sitecore.Data.Items.Item.Recycle()
   at SitecoreSidekick.Services.SitecoreDataAccessService.RecycleItem(String id)
   at ScsContentMigrator.Core.ContentItemInstaller.CleanUnwantedLocalItems()
```

Had a quick look into the code, seems like `SitecoreDataAccessService.RecycleItem` is missing a `SecurityDisabler`?

**Comment by JeffDarchuk** [comment]
Thanks for the bug report, i'll make sure this fix is in the next release.

**Comment by markgibbons25** [comment]
Personally I would think that we would instead disable the `RemoveLocalNotInRemote` option if the user does not have recycle access?

**Comment by vitaliitylyk** [comment]
I have just figured out that this error happens only when doing content migration from Powershell script. In that case there is no context user available.
However, when I run the same migration from UI, it works fine (because I am logged in as admin user).

As far as I can see, `SecurityDisabler` is used all over the code, so I assume the intention was that the migration should ignore security rights? And security access is controlled only on the UI level (users can or cannot use the app).

**Comment by JeffDarchuk** [comment]
it should have a security disabler applied to it.  If a user shouldn't be allowed to delete my thinking is that you'd use the security settings in the configuration to disable access for that user.  Generally i set it up as admin only.

**Comment by JeffDarchuk** [comment]
security disabler has been applied to this method as part of release 1.5.8

**Comment by vitaliitylyk** [comment]
Thanks a lot for the quick fix! Will test it out.
