### ISSUE TITLE
Should SetupTrackerForUnwantedLocalItems be asynchronous?

### ISSUE THREAD

**Issue by vitaliitylyk** [JeffDarchuk/SitecoreSidekick#55]
When `RemoveLocalNotInRemote` is enabled, SideKick is gathering all descendant items for the root Ids (`IContentItemInstaller.SetupTrackerForUnwantedLocalItems`). 

In case there is a big amount of items to sync, this process takes a while and a call to `/scs/cm/cmstartoperation.scsvc` does not return unless that is finished. On large item trees, this call will most likely timeout.

I think it would be better if this code would be running asynchronously as a part of the actual migration and the `/scs/cm/cmstartoperation.scsvc` API call would immediately return, acknowledging that migration operation is registered and returning `OperationId`.

What do you think? This is quite relevant when using Scripting via Powershell, A call to the `/scs/cm/cmstartoperation.scsvc` quite often results into a timeout. After receiving timeout it is not clear if operation has started or not and what is the OperationId.

**Comment by JeffDarchuk** [comment]
it's a possibility.  How much time are you seeing this process take?

**Comment by vitaliitylyk** [comment]
In my case for ~185000 items it can take 4-5 minutes.

**Comment by JeffDarchuk** [comment]
Interesting, in my testing i was using 1M items and it took about 45 seconds.  Thanks for bringing this up, async would likely allow it to work on slower environments, i'll see about adjusting it.

**Comment by JeffDarchuk** [comment]
This has been addressed as you suggested it should in release 1.5.8

**Comment by vitaliitylyk** [comment]
Nice, that was quick, thanks! I have tried to test this and came across a Javascript issue which slipped into the 1.5.8 release, I have created a separate issue for that: https://github.com/JeffDarchuk/SitecoreSidekick/issues/56
