### ISSUE TITLE
[Enhancement] Close Start menu on Desktop when selecting Sitecore Sidekick

### ISSUE THREAD

**Issue by markgibbons25** [JeffDarchuk/SitecoreSidekick#60]
I can see some of the other apps e.g. Publish, Template Manager close the Start menu when you select it, but Sideckick doesn't.
Just a great usability fix, thanks.

**Comment by JeffDarchuk** [comment]
This should be fixed in the latest version 1.5.9.  Can you confirm that it is not?

**Comment by markgibbons25** [comment]
Refreshed browser cache and its fixed. Cheers.
