### ISSUE TITLE
Content Migrator quick diff - problems detecting changes on child nodes

### ISSUE THREAD

**Issue by markgibbons25** [JeffDarchuk/SitecoreSidekick#62]
![image](https://user-images.githubusercontent.com/3212534/97792848-ab6cb180-1c2f-11eb-9869-192b33a0bf69.png)

Splitting this issue out from #58

The mechanism which uses checksums calculated on both the source and target systems to compare seems to have issues in some scenarios. It is hard to set up a test case, but perhaps some debug logging code could be added to the mechanism so that we can see what the comparisons are and why it thinks there are no changes to child nodes / leaf nodes when there are.

**Comment by markgibbons25** [comment]
Haven't seen the above one in a while, but still seeing this one
![image](https://user-images.githubusercontent.com/3212534/109768666-ecf48400-7c44-11eb-971e-52d62200eed2.png)

**Comment by JeffDarchuk** [comment]
Is this an issue that will resolve itself given time, or is it stuck this way?  The process to build that checksum is executed periodically instead of on demand, there's a potential that things get out of sync temporarily.  It's set up to rebuild the checksum after item events or a sync happens, but sometimes it's just not fast enough.  Generally, however, it does get fixed given a little time (like 5-10 minutes)

**Comment by markgibbons25** [comment]
I'd be happy to have it block until the checksum is recalculated, rather than an incorrect calculation. Accuracy over speed, as this stuff can be fairly business critical and missing changes costs time.

**Comment by JeffDarchuk** [comment]
I ask to determine if there's a bug in the process, or just a timing issue.  If it's just a timing issue I could synchronize that somehow, or at least give notification that the diff is being currently built locally or remotely, that would likely be a simpler change.

**Comment by markgibbons25** [comment]
I don't think it's a timing issue to be honest, these items in the screenshot havent changed in weeks, and I just went back in again and confirmed, waited 5 min, and confirmed again. 
But it's definitely a lot better now in 1.5.14 I haven't seen any similar to the very first screenshot.

If you want to try repro, once again probably do non- 'en' language.

**Comment by JeffDarchuk** [comment]
I've been tracking oddities like this for years, i haven't been able to reproduce them however.   That's the hardest part it would seem.  I'll try specifically targetting multi-lingual features to see.  Now that i know my fundamental knowledge of the ref id field was off, that's at least the prime suspect.

**Comment by JeffDarchuk** [comment]
This has been given an overhaul as part of the 1.6.0-alpha1 release.  I suspect things will be more reliable now

**Comment by markgibbons25** [comment]
Looking good!
