### ISSUE TITLE
Error to access to the remote servers: AccessViolationException 

### ISSUE THREAD

**Issue by mercedesamoros** [JeffDarchuk/SitecoreSidekick#65]
Hello! I am getting this error when I try to access to the qa, production enviroments, and after debugging I can see that the headers 
wc.Headers["X-MC-MAC"] ,wc.Headers["X-MC-Nonce"] are missing. 
The shared secrets match. 

![image](https://user-images.githubusercontent.com/61792897/99552490-59f94c00-29bd-11eb-8c3c-6ca37b642be1.png)
![image](https://user-images.githubusercontent.com/61792897/99552768-ad6b9a00-29bd-11eb-87bf-88aad344b356.png)

**Comment by JeffDarchuk** [comment]
without those headers the request would be seen as invalid.  I've seen before where there was a proxy that was changing or removing headers or parameters that caused the request to be invalid.  Check your networking layer and make sure nothing is messing with those properties.  For example i've seen a security proxy that puts something like a "secure=true" query string parameter to the end of the url after scanning it which cause the authentication protocols to fail in Sidekick

**Comment by mercedesamoros** [comment]
Jeff! Thanks very much for your response at the end I made it work. Really good tool. Thanks

**Comment by mercedesamoros** [comment]
Thanks you!
