### ISSUE TITLE
Item skipped without reason

### ISSUE THREAD

**Issue by nixman2** [JeffDarchuk/SitecoreSidekick#70]
so we have two identical sitecore environments.
On the environment A we created an item and subitems.
Going to the environment B we ran Content migrator & saw a white square next to the new content, indicating it only lives on environment A.
All good so far, we pulled the content (including subitems) from A to B and the square became green, as expected.

Next we changed a fields value to read test, on one of the subitems on environment A.
Going to environment B we ran content migrator & saw a red square next to the changed item. Again as expected.

We selected it's parent leaving all the checkboxes selected (we included children) and ran pull.
The report said 1 skipped and nothing else. Without any indication why it skipped the item.

Unchecking the bottom group of checkboxes (itemblaster etc) didn't resolve this.
Right now we can't utilize this tool as it's behaviour can't be explained by us to our business.

We would like to know the reason it's skipped or a fix so the item is updated.

We use SitecoreSidekickContentMigrator nuget package V1.5.11 on Sitecore 9.1.1

**Comment by JeffDarchuk** [comment]
From what i can tell it certainly seems like a bug, although I've never encountered or had others report of anything similar.  Are there any Sidekick related log messages?  Anything else about these items that might be unusual?

**Comment by markgibbons25** [comment]
I've just seen similar behaviour. Ticking "ignore rev ID" and running again brought across the changes.
I think we need some good logging in place so we can help diagnose these.

**Comment by markgibbons25** [comment]
I've spent hours debugging this and finally figured it out. 

https://github.com/JeffDarchuk/SitecoreSidekick/blob/44c77def2f74ca41e72b3107389e3f0a61d48a99/Source/SitecoreSidekick/Services/SitecoreDataAccessService.cs#L65

Usages of `SitecoreDataAccessService` specifically the calls to `GetItemAndChildrenRevision` don't take language into account. So therefore it will just get the default item language, where there might be changes on other language versions but not the default.

Steps to reproduce:
1. Source env: Create item and tree for testing in 'en' version
2. Target env: Pull that tree
3. Source env: Add new language versions in another language, make a change, save
4. Target env: Pull that tree - all items skipped

Workaround: Ticking "ignore rev ID" fixes as it will not call into above code in this case.

**Comment by JeffDarchuk** [comment]
Hmmm, i was under the impression this was a shared field that updated on any item change.  If that's wrong i need to update that.  I'll do a bit of investigating tomorrow.

**Comment by markgibbons25** [comment]
Perhaps it changed at some point, but these days its a fully versioned field 
![image](https://user-images.githubusercontent.com/3212534/108961869-ae4e4f00-76c3-11eb-8124-62c26f36d16e.png)

**Comment by Ricardowouda** [comment]
I can confirm it is a language issue. I'm a colleague of @nixman2. We got several dutch websites in our Sitecore environment which we use with the language "nl-NL". If I change a field on the "nl-NL" version of a datasource it will be skipped when we try to sync it with Sidekick. I we change the same field on the language "en" it will sync correctly.

**Comment by JeffDarchuk** [comment]
Ah, that's an unfortunate mistake i made then.  I'll make sure to get that fixed up soon

**Comment by JeffDarchuk** [comment]
This is addressed and fixed in version `1.5.14` can you please confirm?

**Comment by markgibbons25** [comment]
I can confirm that it seems fixed now, thanks.

**Comment by Ricardowouda** [comment]
updated to version 1.5.14 and I also can confirm it works perfectly now :)

**Comment by JeffDarchuk** [comment]
excellent, thanks for the bug report and the assist debugging
