### ISSUE TITLE
Feature request - Audit log - SQL / Solr logger

### ISSUE THREAD

**Issue by markgibbons25** [JeffDarchuk/SitecoreSidekick#71]
I can see that the implementation of https://github.com/JeffDarchuk/SitecoreSidekick/blob/master/ScsAuditLog/Core/AuditLog.cs is using the file system. This doesn't work well with Azure PaaS. Could we have an implementation where we specify a SQL connection string?

**Comment by JeffDarchuk** [comment]
Yes you are correct that this feature doesn't function well on any of the cloud platforms.  I have been considering options for a while, I think given the current direction of Sitecore converting it to use the same Solr that Sitecore uses would likely be a good option.

**Comment by markgibbons25** [comment]
Yeah I can get on board with Solr.
