### ISSUE TITLE
Suggestion - namespace change

### ISSUE THREAD

**Issue by markgibbons25** [JeffDarchuk/SitecoreSidekick#75]
When looking for dll's in the sitecore bin folder, it is somewhat tricky to find all of the Sidekick dll's as we have some starting with Scs and then the SitecoreSidekick.dll. Side note - now with Sitecore Content Serialization the SCS acronym has been taken over by the platform :'( 
I'd suggest a namespace and assembly name change for all to start with "Sidekick".

Sidekick.Core
Sidekick.ContentMigrator
Sidekick.AuditLog
Sidekick.EditingContext

**Comment by JeffDarchuk** [comment]
There was quite a bit to this one, but i thought it was a good idea and gave it a go.  This is part of the 1.6.0-alpha1 release.  it still needs testing which is why it's alpha, but if you want to check it out feel free.

**Comment by markgibbons25** [comment]
Awesome stuff! Thanks
