### ISSUE TITLE
Feature request - Remember last sync root - auto expand tree

### ISSUE THREAD

**Issue by markgibbons25** [JeffDarchuk/SitecoreSidekick#76]
After doing a pull, and then clicking the back to content migrator button, it would be good if the tree auto-expanded to how it was before, or at least expands to the first item of the selected. It definitely remembers the last choices as if you click pull again it pulls the same item root(s), which is great.

**Comment by JeffDarchuk** [comment]
agreed, that's actually how it's supposed to work, but somewhere along the way it broke and i haven't gotten around to fixing it yet

**Comment by JeffDarchuk** [comment]
this has been fixed in 1.6.0-alpha1

**Comment by markgibbons25** [comment]
Looking good!
