### ISSUE TITLE
Consider optimizing GetContentSelectedRelated

### ISSUE THREAD

**Issue by kamsar** [JeffDarchuk/SitecoreSidekick#8]
Not a big deal for _most_ use cases, but based on our conversation just now we talked about optimizing the number of calls to `GetContentSelectedRelated` (and the remote variant thereof) by changing it as a per-node boolean result to a single call that returns the ancestor ID(s) of the currently selected item into a shared scope.

This would improve scaling on low bandwidth connections as well as folks moving deep content items or those with a lot of sibling parents.

**Comment by JeffDarchuk** [comment]
this has been solved in most recent version with more intelligent request batching
