### ISSUE TITLE
Sitecore 10.1 support - icons

### ISSUE THREAD

**Issue by markgibbons25** [JeffDarchuk/SitecoreSidekick#80]
I'm doing an upgrade to 10.1 and am also testing out the 1.6.0-alpha. 
I notice that icons dont seem to show until you pull the item. I wonder if this is actually a 10.1 issue with the new .dat file data provider.

In this screenshot I have pulled the /sitecore/content item but before that it didn't show the icon same as the others.

![image](https://user-images.githubusercontent.com/3212534/114805859-13cadc00-9de7-11eb-815e-0dc303ff78d8.png)

I haven't seen any other issues yet but will let you know.

**Comment by JeffDarchuk** [comment]
I'm between clients at the moment so i don't have a convenient spot to test, but i think i uncovered what's causing this on my 10.1 install.  could you confirm that it's fixed in alpha2?

**Comment by markgibbons25** [comment]
Will confirm soon, quick question, do you think there could be any problems with content migrator with the source system is sidekick 1.5 and target system is 1.6 alpha, where only language used is 'en' ? A colleague has tried it and didnt see any issues but just wanted to confirm. All good if you have nfi :D

**Comment by JeffDarchuk** [comment]
1.5 to 1.6 should be fully compatible with each other.  Good to go

**Comment by markgibbons25** [comment]
Thanks mate. I can confirm the icons are fixed.
