### ISSUE TITLE
Quick compare UI not picking up new items on local as the only diff

### ISSUE THREAD

**Issue by markgibbons25** [JeffDarchuk/SitecoreSidekick#81]
![image](https://user-images.githubusercontent.com/3212534/118075177-d90e9080-b3f2-11eb-954b-a06888c2c0b3.png)

Where the only difference is a new item on local compared to remote, it doesnt pick these up as a child has changes below it.
Version - 1.6.0 alpha 2

**Comment by JeffDarchuk** [comment]
Hmm, and this isn't something that changes after restarting Sitecore on both the local and remote side of things?

**Comment by markgibbons25** [comment]
aaand I can't reproduce it anymore.. urgh.

**Comment by markgibbons25** [comment]
It still happens off and on. I've had a bit of pushback on this module from the team because of this issue. I realise its somewhat cosmetic but when it comes to business critical content there's a lot on the line. Is there anything we can do for this? A button that force refreshes it on both systems?

**Comment by JeffDarchuk** [comment]
yes, that is quite frustrating.  Any tips on re-creating this?  Without seeing it happen directly it's very difficult to manage.  Only other option would be to add a bit of details about the checksum such as when it was last built, if it's currently running, and the ability to trigger a rebuild on both local and remote.  It would at least give remediation tools for situations like this.
