### ISSUE TITLE
Incompatibility of DefaultLogger with Rainbow 2.1.4

### ISSUE THREAD

**Issue by vitaliitylyk** [JeffDarchuk/SitecoreSidekick#86]
Current implementation of `DefaultLogger` is lacking the `LogSystemMessage` method implementation, which makes Sidekick incompatible with latest Rainbow version (related changes: https://github.com/SitecoreUnicorn/Rainbow/commit/c636a477990db2ccdd7f2fc921f2690aaa8fc0d2).

This results into runtime error when trying to pull content via ContentMigrator:

`Method 'LogSystemMessage' in type 'ScsContentMigrator.CMRainbow.DefaultLogger' from assembly 'ScsContentMigrator, Version=1.5.14.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.`

**Comment by JeffDarchuk** [comment]
Thanks a ton for bringing this up, just released version 1.6 of sidekick today which contains a fix for this error.

**Comment by vitaliitylyk** [comment]
Great, thanks for a quick fix!

**Comment by markgibbons25** [comment]
@JeffDarchuk looks like you didn't push the commit that fixed this yet :)

**Comment by vitaliitylyk** [comment]
Yeah, I have tried version 1.6 and still getting the same error, so looks like smth went wrong @JeffDarchuk

**Comment by JeffDarchuk** [comment]
It's quite difficult to allow it to be used with any version of Rainbow.  However i think i figured it out and tested it more thoroughly this time.  Check out 1.6.1 please.

**Comment by vitaliitylyk** [comment]
Now it works, thx @JeffDarchuk!

**Comment by JeffDarchuk** [comment]
glad to hear it!  Code is updated on master too @markgibbons25
