### ISSUE TITLE
Media icons don't work unless also signed in to remote server

### ISSUE THREAD

**Issue by kamsar** [JeffDarchuk/SitecoreSidekick#9]
![image](https://cloud.githubusercontent.com/assets/103677/26458123/3bee4120-4127-11e7-8482-084803c3e9e6.png)

![image](https://cloud.githubusercontent.com/assets/103677/26458181/676303d6-4127-11e7-8ab4-86ed515a4945.png)

Remote server media icons are being redirected to the login page if unauthenticated, thus breaking the icons.

**Comment by JeffDarchuk** [comment]
this is resolved in the latest version, there's now an icon service that doesn't require login
